### ISSUE TITLE
"Added to Cart" Dialog Blank if Triggered After Session Timeout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/cloud-commerce-spartacus-storefront#3442]
TBD

![Screen Shot 2019-06-27 at 5 02 03 PM](https://user-images.githubusercontent.com/46171897/60303950-dccfc180-9905-11e9-99c1-0dbd8becde5e.png)

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3187

**Comment by marlass** [comment]
That is related to a few topics.

For catching errors in add to cart process event system would be helpful (#5182)

There is a plan for modal refactor, so that is also related (#4823)

I would wait for this ticket for both of those tickets. It might be also fixed by accident with the dialog refactor. 

Look again into it after those fixes.

**Comment by marlass** [comment]
It is not related to auth module, but to feature (added to cart modal)

**Comment by giancorderoortiz** [comment]
Still an issue?

**Comment by giancorderoortiz** [comment]
Still an issue with Spartacus 3.0 and latest develop branch (June 20). 

![Screen Shot 2021-06-20 at 6 47 57 PM](https://user-images.githubusercontent.com/46171897/122690570-54d0d980-d1f8-11eb-92c4-0c36528178d1.png)



@Xymmer Should it be fixed for 4.0?
